apiVersion: v1
kind: Secret
metadata:
  name: hospital-tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ0akNDQVdXZ0F3SUJBZ0lVT2pYOGp3R0Y0Nm1VdG9ndkxtTk0xRFR4NDJZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1ZERVNNQkFHQTFVRUF3d0pJR3B2YzNCcGRHRnNMbXh2WTJGc01CNFhEVEkyTURjeU16RXlNRGN4TUZvWApEVE0xTURjeU16RXlNRGN4TUZvd1ZERVNNQkFHQTFVRUF3d0pJR3B2YzNCcGRHRnNMbXh2WTJGczNSVXdFd1lECktvWklodmNOQVFFQkFRVUFBNG9EQU1DQUdRQ0JCQ1d3UTBiSjR6MUVXQ2RXZkM5cllrQUFBQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdkJqT3BNSFlqUHhZWUp2ZFp3QUFBQUVDQVFFQUF3S0J3Z1FBQUFBREFRQUJBaUVBCnZCK293UlFBQUFBQkFRQUFCQUVDQVFEOU16UXlOekEwTkRjME5UYzE2Z3dCQUFBQkFRQUFCQUVDQVFEOU16UXkKTnpBME5EYzBOVGMxNmd3QkFBQUJBUUFBQkFFQ0FRRDlNeFF5TnpBME5EYzBOVGMxNmd3QkFBQUJBUUFBQkFFQwpBUUQ5TXpR