import dotenv from "dotenv";
dotenv.config();

const NODE_ENV = process.env.NODE_ENV;
const PORT = process.env.PORT || 4777;
const DB_CONNECTION_STRING = process.env.DB_CONNECTION_STRING;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
const APPOINTMENT_SERVICE_BASE_URL = process.env.APPOINTMENT_SERVICE_BASE_URL

export {
    NODE_ENV,
    PORT,
    DB_CONNECTION_STRING,
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET,
    APPOINTMENT_SERVICE_BASE_URL
};
